---
# tasks file for mysqldb

- include: install_mysql.yml
- include: start_mysql.yml
- include: mysql_user_passwd.yml
- include: mysql_dbname.yml







apiVersion: apps/v1
kind: Deployment 
metadata:
 name: java-ms
 labels:
   app: java-ms
spec:
  replicas: 1
  selector:
   matchLabels: 
     app: java-ms
  template:
    metadata:
      labels:
        app: java-ms 
    spec: 
     containers:
     - name: java-ms 
       image: ankit1111/account-service
       ports: 
       - containerPort: 2222
         protocol: TCP
     imagePullSecrets:
     - name: java






     =---------

apiVersion: v1
kind: Service
metadata:
 name: java-ms-services
 labels:
   app: java-ms
        
spec:
 type: NodePort
 ports:
  - port: 2222
    targetPort: 2222
    nodePort: 30001
 selector:
    app: java-ms


    -------


apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-nginx
spec:
 storageClassName: manual 
 capacity:
   storage: 2G
 accessModes: 
  - ReadWriteOnce  
 hostPath:
   path: "/opt/backup"


   -----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
 storageClassName: manual
 accessModes: 
   - ReadWriteOnce
 resources:
   requests:
    storage: 2Gi
-------
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
     labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pvc-nginx
      volumes:
      - name: pvc-nginx
        persistentVolumeClaim:
         claimName: pvc-nginx


    ip:nodeport    services   pods
                              pods 
                              pods  



    nodePort-----  30000-32767
    clusterip---inter
    loadbalancer----

    secret------ 64bit enctypted--- credentail 
    configmap--   anyon-----key value 

    kubectl create secret docker-registry java   --docker-username=ankit11111 --docker-password=miet@1234 